services:
  web:
    build:
      context: .
      dockerfile: docker/production/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      - laravel-production

  php-fpm:
    build:
      context: .
      dockerfile: docker/common/php-fpm/Dockerfile
      target: production
    env_file:
      - .env
    networks:
      - laravel-production

  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: promptagent
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data-production:/var/lib/postgresql/data
    networks:
      - laravel-production

  redis:
    image: redis:alpine
    networks:
      - laravel-production

networks:
  laravel-production:

volumes:
  postgres-data-production:
